-- Imagenes descargadas y servidas desde el propio dominio.
-- Antes la tienda enlazaba 167 fotos alojadas en sitios de terceros: se rompen
-- solas cuando el host activa proteccion de hotlink (ya pasaba con palmtalk y
-- palmpedia, 29 de ellas daban 403) y dependen de que nadie las mueva.
-- 129 traidas, redimensionadas a 1200px y guardadas en /plantas/.
-- La procedencia de cada una queda registrada en
-- scripts/rescate-viejo/atribucion-imagenes.json para poder atribuir o sustituir.
-- Las 38 que no se pudieron traer (403 en su mayoria) conservan su enlace externo.

UPDATE public.plants SET images=ARRAY['/plantas/chamaedorea-radicalis-1.jpg','/plantas/chamaedorea-radicalis-2.jpg','/plantas/chamaedorea-radicalis-3.jpg','/plantas/chamaedorea-radicalis-4.jpg','/plantas/chamaedorea-radicalis-5.jpg']::text[], primary_image='/plantas/chamaedorea-radicalis-1.jpg' WHERE slug='chamaedorea-radicalis';
UPDATE public.plants SET images=ARRAY['/plantas/geonoma-undata-1.jpg','/plantas/geonoma-undata-2.jpg','/plantas/geonoma-undata-3.jpg','/plantas/geonoma-undata-4.jpg','/plantas/geonoma-undata-5.jpg','/plantas/geonoma-undata-6.jpg','/plantas/geonoma-undata-7.jpg','/plantas/geonoma-undata-8.jpg','/plantas/geonoma-undata-9.jpg','/plantas/geonoma-undata-10.jpg','/plantas/geonoma-undata-11.jpg','/plantas/geonoma-undata-12.jpg','/plantas/geonoma-undata-13.jpg','/plantas/geonoma-undata-1.jpg','/plantas/geonoma-undata-2.jpg','/plantas/geonoma-undata-3.jpg','/plantas/geonoma-undata-4.jpg','/plantas/geonoma-undata-5.jpg']::text[], primary_image='/plantas/geonoma-undata-1.jpg' WHERE slug='geonoma-undata';
UPDATE public.plants SET images=ARRAY['/plantas/prestoea-acuminata-var-acuminata-1.jpg','https://www.palmpedia.net/palmsforcal/images/thumb/6/64/Prestoea_acuminata_var_acuminata.JPG/337px-Prestoea_acuminata_var_acuminata.JPG','/plantas/prestoea-acuminata-var-acuminata-3.jpg']::text[], primary_image='/plantas/prestoea-acuminata-var-acuminata-1.jpg' WHERE slug='prestoea-acuminata-var-acuminata';
UPDATE public.plants SET images=ARRAY['/plantas/cyphophoenix-nucele-1.jpg','https://www.palmtalk.org/forum/uploads/monthly_2017_03/IMG_0304.thumb.JPG.8fba78bdfced50293eabb73daf5f72b9.JPG','https://www.palmpedia.net/palmsforcal/images/thumb/7/78/Cyphophoenix_nucele_crownshaft_Ha.JPG/337px-Cyphophoenix_nucele_crownshaft_Ha.JPG','/plantas/cyphophoenix-nucele-4.jpg','/plantas/cyphophoenix-nucele-5.jpg']::text[], primary_image='/plantas/cyphophoenix-nucele-1.jpg' WHERE slug='cyphophoenix-nucele';
UPDATE public.plants SET images=ARRAY['/plantas/dictyocaryum-lamarckianum-1.jpg','/plantas/dictyocaryum-lamarckianum-2.jpg','https://www.palmtalk.org/forum/uploads/monthly_2016_10/IMG_3182.jpg.c71071a76833d0213753f66251c5c003.jpg','/plantas/dictyocaryum-lamarckianum-4.jpg']::text[], primary_image='/plantas/dictyocaryum-lamarckianum-1.jpg' WHERE slug='dictyocaryum-lamarckianum';
UPDATE public.plants SET images=ARRAY['/plantas/araucaria-angustifolia-1.jpg','/plantas/araucaria-angustifolia-2.jpg','https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Itaimbezinho_-_Parque_Nacional_Aparados_da_Serra_33.JPG/2560px-Itaimbezinho_-_Parque_Nacional_Aparados_da_Serra_33.JPG','/plantas/araucaria-angustifolia-4.jpg']::text[], primary_image='/plantas/araucaria-angustifolia-1.jpg' WHERE slug='araucaria-angustifolia';
UPDATE public.plants SET images=ARRAY['/plantas/archontophoenix-cunninghamiana-1.jpg','/plantas/archontophoenix-cunninghamiana-2.jpg','/plantas/archontophoenix-cunninghamiana-3.jpg','/plantas/archontophoenix-cunninghamiana-4.jpg']::text[], primary_image='/plantas/archontophoenix-cunninghamiana-1.jpg' WHERE slug='archontophoenix-cunninghamiana';
UPDATE public.plants SET images=ARRAY['/plantas/caryota-mitis-1.jpg','/plantas/caryota-mitis-2.jpg','/plantas/caryota-mitis-3.jpg','/plantas/caryota-mitis-4.jpg']::text[], primary_image='/plantas/caryota-mitis-1.jpg' WHERE slug='caryota-mitis';
UPDATE public.plants SET images=ARRAY['/plantas/ceratozamia-hildae-1.jpg','/plantas/ceratozamia-hildae-2.jpg','/plantas/ceratozamia-hildae-3.jpg','/plantas/ceratozamia-hildae-4.jpg']::text[], primary_image='/plantas/ceratozamia-hildae-1.jpg' WHERE slug='ceratozamia-hildae';
UPDATE public.plants SET images=ARRAY['/plantas/chamaedorea-microspadix-1.jpg','/plantas/chamaedorea-microspadix-2.jpg','https://www.palmtalk.org/forum/uploads/monthly_2022_05/20220505_150340.jpg.8ac258d6af15c66ca6da44ecd87f5738.jpg','/plantas/chamaedorea-microspadix-4.jpg','/plantas/chamaedorea-microspadix-5.jpg']::text[], primary_image='/plantas/chamaedorea-microspadix-1.jpg' WHERE slug='chamaedorea-microspadix';
UPDATE public.plants SET images=ARRAY['/plantas/chamaedorea-tepejilote-1.jpg','/plantas/chamaedorea-tepejilote-2.jpg','/plantas/chamaedorea-tepejilote-3.jpg','/plantas/chamaedorea-tepejilote-4.jpg']::text[], primary_image='/plantas/chamaedorea-tepejilote-1.jpg' WHERE slug='chamaedorea-tepejilote';
UPDATE public.plants SET images=ARRAY['/plantas/chambeyronia-lepidota-mid-elevation-1.jpg','/plantas/chambeyronia-lepidota-mid-elevation-2.jpg','/plantas/chambeyronia-lepidota-mid-elevation-3.jpg','https://www.palmpedia.net/wiki/images/thumb/b/b8/P1010800.JPG/337px-P1010800.JPG']::text[], primary_image='/plantas/chambeyronia-lepidota-mid-elevation-1.jpg' WHERE slug='chambeyronia-lepidota-mid-elevation';
UPDATE public.plants SET images=ARRAY['/plantas/dracaena-draco-madeira-1.jpg','/plantas/dracaena-draco-madeira-2.jpg','/plantas/dracaena-draco-madeira-3.jpg','/plantas/dracaena-draco-madeira-4.jpg']::text[], primary_image='/plantas/dracaena-draco-madeira-1.jpg' WHERE slug='dracaena-draco-madeira';
UPDATE public.plants SET images=ARRAY['/plantas/euphorbia-francoisii-1.jpg','/plantas/euphorbia-francoisii-2.jpg','/plantas/euphorbia-francoisii-3.jpg','/plantas/euphorbia-francoisii-4.jpg']::text[], primary_image='/plantas/euphorbia-francoisii-1.jpg' WHERE slug='euphorbia-francoisii';
UPDATE public.plants SET images=ARRAY['/plantas/ixora-margaretae-1.jpg','/plantas/ixora-margaretae-2.jpg','/plantas/ixora-margaretae-3.jpg','/plantas/ixora-margaretae-4.jpg']::text[], primary_image='/plantas/ixora-margaretae-1.jpg' WHERE slug='ixora-margaretae';
UPDATE public.plants SET images=ARRAY['/plantas/livistona-decora-1.jpg','/plantas/livistona-decora-2.jpg','https://cdn-ikpmiob.nitrocdn.com/RvvBoOylnRxQzWxXRKmvmlmchysxbOTV/assets/images/optimized/rev-7114f0c/palmseedlings.com/wp-content/uploads/2024/04/Livistona-Decora-4.webp','/plantas/livistona-decora-4.jpg']::text[], primary_image='/plantas/livistona-decora-1.jpg' WHERE slug='livistona-decora';
UPDATE public.plants SET images=ARRAY['/plantas/loxococcus-rupicola-1.jpg','/plantas/loxococcus-rupicola-2.jpg','/plantas/loxococcus-rupicola-3.jpg','/plantas/loxococcus-rupicola-4.jpg','/plantas/loxococcus-rupicola-5.jpg']::text[], primary_image='/plantas/loxococcus-rupicola-1.jpg' WHERE slug='loxococcus-rupicola';
UPDATE public.plants SET images=ARRAY['/plantas/magnolia-campbellii-1.jpg','/plantas/magnolia-campbellii-2.jpg','/plantas/magnolia-campbellii-3.jpg','/plantas/magnolia-campbellii-4.jpg']::text[], primary_image='/plantas/magnolia-campbellii-1.jpg' WHERE slug='magnolia-campbellii';
UPDATE public.plants SET images=ARRAY['/plantas/magnolia-grandiflora-1.jpg','/plantas/magnolia-grandiflora-2.jpg','/plantas/magnolia-grandiflora-3.jpg','/plantas/magnolia-grandiflora-4.jpg','/plantas/magnolia-grandiflora-5.jpg']::text[], primary_image='/plantas/magnolia-grandiflora-1.jpg' WHERE slug='magnolia-grandiflora';
UPDATE public.plants SET images=ARRAY['/plantas/bentinckia-condapanna-1.jpg','https://www.palmtalk.org/forum/uploads/monthly_2016_09/P1030440.jpg.4aebd10403fc1c9ac0e3599fb3567c1c.jpg','/plantas/bentinckia-condapanna-3.jpg','/plantas/bentinckia-condapanna-4.jpg']::text[], primary_image='/plantas/bentinckia-condapanna-1.jpg' WHERE slug='bentinckia-condapanna';
UPDATE public.plants SET images=ARRAY['/lovable-uploads/06e39b13-24ac-425d-aaba-e54afa8e9a13.png','/lovable-uploads/9ec90b24-0543-43f9-8fbc-9e0550441101.png','/lovable-uploads/e2d5dc14-7a7d-4068-9048-41c51c5b3e3e.png','/lovable-uploads/8dd65cc2-e17d-4d6d-9bf1-f6930328f729.png','/lovable-uploads/9173c699-a4ce-47c6-915d-47ddd7101b34.png','/lovable-uploads/0e644766-bd72-43c9-ba64-16a24ad9c928.png']::text[], primary_image='/lovable-uploads/06e39b13-24ac-425d-aaba-e54afa8e9a13.png' WHERE slug='rhopalostylis-sapida-var-oceana';
UPDATE public.plants SET images=ARRAY['/plantas/phormium-cookianum-1.jpg','/plantas/phormium-cookianum-2.jpg','/plantas/phormium-cookianum-3.jpg','/plantas/phormium-cookianum-4.jpg']::text[], primary_image='/plantas/phormium-cookianum-1.jpg' WHERE slug='phormium-cookianum';
UPDATE public.plants SET images=ARRAY['/plantas/ptychosperma-elegans-1.jpg','/plantas/ptychosperma-elegans-2.jpg','/plantas/ptychosperma-elegans-3.jpg','/plantas/ptychosperma-elegans-4.jpg','/plantas/ptychosperma-elegans-5.jpg']::text[], primary_image='/plantas/ptychosperma-elegans-1.jpg' WHERE slug='ptychosperma-elegans';
UPDATE public.plants SET images=ARRAY['/lovable-uploads/be0531d2-cf9b-4f2c-8ec7-e758b8dbfd69.png','/lovable-uploads/b04dba5e-73cf-4818-8829-a26db8d884c2.png','/lovable-uploads/7276866f-a573-4959-99df-ecc5c91546f9.png','/lovable-uploads/3576febc-43a5-46d0-a625-0c5e00fa5a62.png','/plantas/chamaedorea-elegans-negrita-1.jpg','/plantas/chamaedorea-elegans-negrita-2.jpg','https://www.palmtalk.org/forum/uploads/monthly_2026_01/IMG_8313.thumb.jpeg.4629688e7cdf16edacb55b28fb3a81fd.jpeg','https://www.palmtalk.org/forum/uploads/monthly_2017_07/5967efec4cd88_Chamaedoreaelegansfront01.jpg.c36ef348a2315a9579168fc6c7f0fe36.jpg']::text[], primary_image='/lovable-uploads/be0531d2-cf9b-4f2c-8ec7-e758b8dbfd69.png' WHERE slug='chamaedorea-elegans-negrita';
UPDATE public.plants SET images=ARRAY['/plantas/rhopalostylis-baueri-var-cheesemanii-1.jpg','/plantas/rhopalostylis-baueri-var-cheesemanii-2.jpg','/plantas/rhopalostylis-baueri-var-cheesemanii-3.jpg','/plantas/rhopalostylis-baueri-var-cheesemanii-4.jpg']::text[], primary_image='/plantas/rhopalostylis-baueri-var-cheesemanii-1.jpg' WHERE slug='rhopalostylis-baueri-var-cheesemanii';
UPDATE public.plants SET images=ARRAY['/plantas/trachycarpus-nanus-1.jpg','https://www.palmtalk.org/forum/uploads/monthly_2024_09/IMG_5744.jpeg.273fa75234920fff9cb6a0e06834cb35.jpeg','/plantas/trachycarpus-nanus-3.jpg','https://www.palmtalk.org/forum/uploads/monthly_2017_08/20170830_181116.jpg.45f88efda4f3e1bab5ff571b7b5bd89d.jpg','/plantas/trachycarpus-nanus-5.jpg']::text[], primary_image='/plantas/trachycarpus-nanus-1.jpg' WHERE slug='trachycarpus-nanus';
UPDATE public.plants SET images=ARRAY['/plantas/trachycarpus-princeps-stone-gate-1.jpg','/plantas/trachycarpus-princeps-stone-gate-2.jpg','/plantas/trachycarpus-princeps-stone-gate-3.jpg','/plantas/trachycarpus-princeps-stone-gate-4.jpg']::text[], primary_image='/plantas/trachycarpus-princeps-stone-gate-1.jpg' WHERE slug='trachycarpus-princeps-stone-gate';
UPDATE public.plants SET images=ARRAY['/plantas/vitis-cognitae-1.jpg','/plantas/vitis-cognitae-2.jpg','https://www.guiaverde.com/files/plant/14161057.jpg','/plantas/vitis-cognitae-4.jpg']::text[], primary_image='/plantas/vitis-cognitae-1.jpg' WHERE slug='vitis-cognitae';
UPDATE public.plants SET images=ARRAY['/plantas/wallichia-disticha-1.jpg','/plantas/wallichia-disticha-2.jpg','https://www.palmtalk.org/forum/uploads/monthly_2015_12/5664cae09e91b_Walichiadisticha008.JPG.c7dfa28998cdf45bb460bb932a1c8a72.JPG','https://www.palmtalk.org/forum/uploads/monthly_2015_12/image.jpeg.e7a8778966cbd826650a8aacce7c725e.jpeg']::text[], primary_image='/plantas/wallichia-disticha-1.jpg' WHERE slug='wallichia-disticha';
UPDATE public.plants SET images=ARRAY['https://palmpedia.net/wiki/images/thumb/c/c1/56660fb815adc_SabalLisa0212-7-15.JPG.5f16cd602203ac4eaca8774e9a042839.JPG/407px-56660fb815adc_SabalLisa0212-7-15.JPG.5f16cd602203ac4eaca8774e9a042839.JPG','https://www.palmtalk.org/forum/uploads/monthly_2020_12/1870204520_SabalpalmettoLisa0104-30-19.JPG.d7a67d40b821f67701a232f55efff923.JPG','/plantas/sabal-palmetto-lisa-3.jpg','/plantas/sabal-palmetto-lisa-4.jpg','/plantas/sabal-palmetto-lisa-5.jpg']::text[], primary_image='/plantas/sabal-palmetto-lisa-3.jpg' WHERE slug='sabal-palmetto-lisa';
UPDATE public.plants SET images=ARRAY['https://www.palmtalk.org/forum/uploads/monthly_2025_02/mmexport1738899208685.jpeg.2060616cba49616e5580fb0b12a75e78.jpeg','/plantas/trachycarpus-sp-himgarda-2.jpg','https://www.palmtalk.org/forum/uploads/monthly_2025_02/mmexport1738899214056.jpeg.ec9f0e4a4ec05d646391ea0b64d44c03.jpeg','/plantas/trachycarpus-sp-himgarda-4.jpg']::text[], primary_image='/plantas/trachycarpus-sp-himgarda-2.jpg' WHERE slug='trachycarpus-sp-himgarda';
UPDATE public.plants SET images=ARRAY['/plantas/butia-yatay-1.jpg','https://bananalicious.pl/environment/cache/images/0_0_productGfx_2158/ButiaYatay01.jpg','/plantas/butia-yatay-3.jpg','/plantas/butia-yatay-4.jpg']::text[], primary_image='/plantas/butia-yatay-1.jpg' WHERE slug='butia-yatay';
UPDATE public.plants SET images=ARRAY['https://www.palmtalk.org/forum/uploads/monthly_2016_02/IMG_0059.JPG.db6f8444f1c59c69c6bdbb6067e6c202.JPG','/plantas/zamia-sp-jamaican-giant-2.jpg','https://www.palmtalk.org/forum/uploads/monthly_2016_02/IMG_0060.JPG.50e5892437c5e5335a706eb7c5af15ae.JPG','https://www.palmtalk.org/forum/uploads/monthly_2017_01/IMG_0565.JPG.68acf31df16a77edc1d5918f2c6b881b.JPG']::text[], primary_image='/plantas/zamia-sp-jamaican-giant-2.jpg' WHERE slug='zamia-sp-jamaican-giant';
UPDATE public.plants SET images=ARRAY['/lovable-uploads/a04b7d73-9b68-4e31-9174-3d181aad491c.png','/lovable-uploads/9b38e27d-78c3-4b53-a08a-b3441009766c.png','/lovable-uploads/572c0131-eb0d-4fcf-9b74-8f1e4100f427.png','/lovable-uploads/1e817628-12d6-4836-9977-07c3012a0df1.png','/plantas/magnolia-laevifolia-1.jpg','/plantas/magnolia-laevifolia-2.jpg','/plantas/magnolia-laevifolia-3.jpg','/plantas/magnolia-laevifolia-4.jpg','/plantas/magnolia-laevifolia-5.jpg']::text[], primary_image='/lovable-uploads/a04b7d73-9b68-4e31-9174-3d181aad491c.png' WHERE slug='magnolia-laevifolia';
UPDATE public.plants SET images=ARRAY['/lovable-uploads/83cb91af-99bc-45b2-813b-ff789c073d75.png','/lovable-uploads/1e90a912-b532-4f36-b161-098738e1c354.png','/lovable-uploads/ec0403a1-5f5f-43e3-8846-bf343401cf48.png','/lovable-uploads/5cce3c2f-5660-474e-89d8-0442d95afd2b.png','https://www.palmtalk.org/forum/uploads/monthly_2015_10/Sabal_miamiensis_01_7-10-15.JPG.1f3351ac398262368f3d0a183cdc9dc5.JPG','https://www.palmtalk.org/forum/uploads/monthly_2015_12/5664c4f83c733_Sabalmiamiensis026-16-15.JPG.42b11b12f0561b8527ccd08c070f2122.JPG','https://www.palmtalk.org/forum/uploads/monthly_2015_10/IMG_0167.JPG.a2203519c8c7c9c8594681b12e3ae507.JPG','https://www.palmtalk.org/forum/uploads/monthly_2019_10/1256291832_Sabalmiamiensis0110-28-19.JPG.4bf0212d720bf86b39300381c20f91da.JPG']::text[], primary_image='/lovable-uploads/83cb91af-99bc-45b2-813b-ff789c073d75.png' WHERE slug='sabal-miamiensis';
UPDATE public.plants SET images=ARRAY['/plantas/sabal-causiarum-1.jpg','https://www.palmtalk.org/forum/uploads/monthly_2018_11/SCausiarum2018oct.jpg.bc6ca45cfdb0f0cac92d4808353ace90.jpg','https://www.plantdelights.com/cdn/shop/files/Sabal-palmarum-Just-Cause.i-16952.s-67775.r-1_008bdf0e-0afb-4761-85ef-b0e26e644630_600x.jpg?v=1765556599','https://www.palmtalk.org/forum/uploads/monthly_2023_10/IMG_9543.JPG.c48bfc59318457564b2b88f809254508.JPG']::text[], primary_image='/plantas/sabal-causiarum-1.jpg' WHERE slug='sabal-causiarum';
UPDATE public.plants SET images=ARRAY['/plantas/syagrus-romanzoffiana-1.jpg','/plantas/syagrus-romanzoffiana-2.jpg','/plantas/syagrus-romanzoffiana-3.jpg','/plantas/syagrus-romanzoffiana-4.jpg']::text[], primary_image='/plantas/syagrus-romanzoffiana-1.jpg' WHERE slug='syagrus-romanzoffiana';
UPDATE public.plants SET images=ARRAY['/plantas/podocarpus-macrophyllus-1.jpg','/plantas/podocarpus-macrophyllus-2.jpg','/plantas/podocarpus-macrophyllus-3.jpg','/plantas/podocarpus-macrophyllus-4.jpg','/plantas/podocarpus-macrophyllus-5.jpg']::text[], primary_image='/plantas/podocarpus-macrophyllus-1.jpg' WHERE slug='podocarpus-macrophyllus';
UPDATE public.plants SET images=ARRAY['/plantas/pritchardia-hillebrandii-1.jpg','https://www.palmtalk.org/forum/uploads/monthly_2019_05/221367473_PritchardiahillebrandiiIPS1.jpg.d75db1d948d758ab191927e8d362dff4.jpg','/plantas/pritchardia-hillebrandii-3.jpg','/plantas/pritchardia-hillebrandii-4.jpg','/plantas/pritchardia-hillebrandii-5.jpg']::text[], primary_image='/plantas/pritchardia-hillebrandii-1.jpg' WHERE slug='pritchardia-hillebrandii';
UPDATE public.plants SET images=ARRAY['https://www.palmtalk.org/forum/uploads/monthly_2019_01/65DD3B39-C231-46BA-AA56-90492CE4C2F2.jpeg.652a0cbf61114f5728e070d707eeaf91.jpeg','/plantas/burretiokentia-hapala-2.jpg','/plantas/burretiokentia-hapala-3.jpg','/plantas/burretiokentia-hapala-4.jpg']::text[], primary_image='/plantas/burretiokentia-hapala-2.jpg' WHERE slug='burretiokentia-hapala';
