-- Las 4 plantas que el volcado de rescate perdio, recuperadas del proyecto
-- original tras reactivarlo. Todas traen fotos y datos completos:
--   Prestoea acuminata var. acuminata  150 EUR  (la mas cara del catalogo)
--   Butia yatay / Sabal casuarium / Syagrus romanzoffiana   15 EUR c/u
-- Sus slugs originales llevan espacios finales; se normalizan al insertarlas.

INSERT INTO public.plants ("name", "scientific_name", "slug", "description", "short_description", "price", "stock_qty", "container_size", "growth_rate", "mature_height", "mature_width", "origin_country", "origin_region", "native_habitat", "care_instructions", "curious_facts", "specifications", "images", "meta_title", "meta_description", "is_active", "is_featured", "display_order", "common_name", "plant_type", "exposure", "climate_zones", "min_temp_c", "water", "humidity", "plant_use", "rarity", "difficulty", "notes", "family", "image_alt_text", "reference_url", "hardiness_zones", "product_images", "tags")
VALUES ('Butia yatay', 'Butia yatay', 'butia-yatay', 'La Butia yatay es una de las palmeras más elegantes y majestuosas del género Butia, destacando por su imponente estípite solitario que puede alcanzar los 12 metros de altura. Sus hojas son de un color verde glauco o azulado, fuertemente arqueadas, lo que le otorga un aspecto plumoso y sofisticado. Es originaria del sur de Brasil, Uruguay y el noreste de Argentina, donde forma extensos palmares. En cultivo, es sumamente apreciada por su resistencia al frío, soportando heladas de hasta -10°C una vez establecida. Prefiere exposiciones a pleno sol y suelos bien drenados, siendo muy tolerante a la sequía y a los vientos fuertes. Produce racimos de frutos comestibles de sabor agridulce, muy utilizados localmente para jaleas y licores. Es una opción excelente para jardines mediterráneos y templados donde se busque un punto focal de bajo mantenimiento y gran impacto visual. Su crecimiento es lento pero constante, lo que garantiza una estructura sólida y duradera en el paisaje.', 'Majestuosa palmera de hojas azuladas y arqueadas, extremadamente resistente al frío y la sequía.', 15, 0, '30-50 litros', 'slow', '8-12 m', '3-5 m', 'AR', 'Entre Ríos, Argentina', 'Sabanas y pastizales arenosos del noreste de Argentina, Uruguay y sur de Brasil, formando comunidades densas llamadas palmares.', '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, ARRAY['https://semillasdelmundo.com/wp-content/uploads/2025/02/Butia-Yatai-Seeds-semillas-del-mundo.jpeg','https://bananalicious.pl/environment/cache/images/0_0_productGfx_2158/ButiaYatay01.jpg','https://http2.mlstatic.com/D_NQ_NP_682347-MLM47798439525_102021-O.webp','https://antropocene.it/wp-content/uploads/2023/10/Butia_yatay.jpeg']::text[], 'Butia yatay | Palmera de Colección', 'Compra Butia yatay, la elegante palma de hojas azuladas resistente al frío. Ideal para jardines mediterráneos. Envíos desde nuestro vivero especializado.', TRUE, FALSE, 0, 'Palma Yatay', 'palm', ARRAY['sol']::text[], ARRAY['mediterráneo','templado','subtropical','árido']::text[], -10, 'low', 'low', ARRAY['exterior','jardin','maceta']::text[], 'uncommon', 'easy', 'Identificación confirmada al 100%. Especie muy estable taxonómicamente. Muy valorada en paisajismo por su color azulado y resistencia. Confianza en temperatura mínima: 0.9. Confianza en rareza: 0.8.', 'Arecaceae', 'Butia yatay palmera azulada', 'https://www.gbif.org/species/2735150', ARRAY['8b','9a','9b','10a','10b']::text[], NULL, ARRAY['azulada','resistente al frío','frutos comestibles','mediterránea','colección']::text[])
ON CONFLICT (slug) DO UPDATE SET images=EXCLUDED.images, primary_image=EXCLUDED.primary_image, price=EXCLUDED.price, is_active=EXCLUDED.is_active;

INSERT INTO public.plants ("name", "scientific_name", "slug", "description", "short_description", "price", "stock_qty", "container_size", "growth_rate", "mature_height", "mature_width", "origin_country", "origin_region", "native_habitat", "care_instructions", "curious_facts", "specifications", "images", "meta_title", "meta_description", "is_active", "is_featured", "display_order", "common_name", "plant_type", "exposure", "climate_zones", "min_temp_c", "water", "humidity", "plant_use", "rarity", "difficulty", "notes", "family", "image_alt_text", "reference_url", "hardiness_zones", "product_images", "tags")
VALUES ('Prestoea acuminata var. acuminata', 'Prestoea acuminata var. acuminata', 'prestoea-acuminata-var-acuminata', 'La Prestoea acuminata var. acuminata es una palmera elegante y esbelta, originaria de las selvas nubladas de América Central y del Sur. Se distingue por su tronco solitario, liso y grisáceo, coronado por un capitel verde y frondas pinnadas de un verde vibrante que caen con gracia. A diferencia de otras palmeras tropicales, esta variedad prospera en altitudes elevadas, lo que le otorga una resistencia notable a temperaturas más frescas, aunque no tolera heladas intensas. 

En cuanto a sus cuidados, requiere un entorno que simule su hábitat de bosque montano: alta humedad ambiental, riego constante para mantener el sustrato húmedo (pero bien drenado) y una exposición de semisombra o luz filtrada, ya que el sol directo intenso puede quemar sus hojas. Es una opción excepcional para coleccionistas que buscan una palmera con aspecto tropical pero que prefieren climas subtropicales o invernaderos frescos. Su crecimiento es moderado y aporta una estructura vertical muy estética tanto en jardines protegidos como en grandes contenedores.', 'Elegante palmera de montaña con tronco esbelto y capitel verde, ideal para zonas de semisombra y alta humedad.', 150, 0, '15-30 cm pot', 'moderate', '5-12 m', '2-3 m', 'CO', 'Andes y Centroamérica', 'Bosques nublados y selvas montanas desde Centroamérica hasta los Andes en Sudamérica, creciendo a menudo en pendientes húmedas.', '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, ARRAY['https://qsjnjitjbegtrxgwqygg.supabase.co/storage/v1/object/public/plant-images/plants/1772239051314-lpdyqqwaxom.jpeg','https://www.palmpedia.net/palmsforcal/images/thumb/6/64/Prestoea_acuminata_var_acuminata.JPG/337px-Prestoea_acuminata_var_acuminata.JPG','https://www.palmpedia.net/palmsforcal/images/thumb/e/ea/Prestoea_acuminata_var._acuminata_DArold.jpg/337px-Prestoea_acuminata_var._acuminata_DArold.jpg']::text[], 'Prestoea acuminata var. acuminata | Palmera de Montaña', 'Compra Prestoea acuminata var. acuminata, una palmera de montaña elegante y resistente al fresco. Ideal para climas subtropicales y coleccionistas. Envío expert', TRUE, FALSE, 0, 'Palma de Manaca', 'palm', ARRAY['semisombra','sombra']::text[], ARRAY['tropical','subtropical','templado']::text[], 1, 'high', 'high', ARRAY['exterior','jardin','maceta']::text[], 'rare', 'intermediate', 'Identificación confirmada como la variedad tipo. Es menos común en cultivo que la var. montana. Confianza alta en datos climáticos debido a su origen altitudinal. Scientific_name: 0.98, Family: 1.0, Min_temp_c: 0.85, Rarity: 0.9.', 'Arecaceae', 'Prestoea acuminata var. acuminata planta palmera', 'https://www.gbif.org/species/2735160', ARRAY['10a','10b','11a']::text[], NULL, ARRAY['tropical','rara','coleccionista','palmera de montaña','exótica']::text[])
ON CONFLICT (slug) DO UPDATE SET images=EXCLUDED.images, primary_image=EXCLUDED.primary_image, price=EXCLUDED.price, is_active=EXCLUDED.is_active;

INSERT INTO public.plants ("name", "scientific_name", "slug", "description", "short_description", "price", "stock_qty", "container_size", "growth_rate", "mature_height", "mature_width", "origin_country", "origin_region", "native_habitat", "care_instructions", "curious_facts", "specifications", "images", "meta_title", "meta_description", "is_active", "is_featured", "display_order", "common_name", "plant_type", "exposure", "climate_zones", "min_temp_c", "water", "humidity", "plant_use", "rarity", "difficulty", "notes", "family", "image_alt_text", "reference_url", "hardiness_zones", "product_images", "tags")
VALUES ('Sabal casuarium', 'Sabal causiarum', 'sabal-causiarum', 'Sabal causiarum es una de las palmeras más majestuosas y robustas del género Sabal. Originaria de Puerto Rico, las Islas Vírgenes y La Española, destaca por su tronco masivo y liso de color gris claro, que puede alcanzar diámetros considerables. Sus hojas son costapalmadas, de un verde azulado o grisáceo, y forman una corona densa y esférica muy atractiva. Es una especie extremadamente resistente una vez establecida, capaz de tolerar vientos huracanados y periodos de sequía. En cuanto a su cultivo, prefiere una exposición a pleno sol para desarrollar su máximo potencial. Aunque su crecimiento inicial es algo lento, acelera notablemente una vez que el tronco comienza a formarse. Es ideal para grandes jardines, avenidas o como ejemplar solitario donde su porte arquitectónico pueda destacar. Requiere suelos bien drenados, aunque se adapta a diversos tipos de sustrato, incluidos los calizos. Es una opción excelente para climas mediterráneos y subtropicales debido a su notable resistencia al frío moderado.', 'Impresionante palmera de tronco masivo y grisáceo, muy resistente al viento y al frío moderado.', 15, 2, '15-30 litros (ejemplares jóvenes)', 'slow', '10-15 m', '4-6 m', 'PR', 'Puerto Rico y el Caribe', 'Bosques secos y zonas costeras de Puerto Rico, La Española y las Islas Vírgenes, a menudo en suelos de origen calizo.', '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, ARRAY['https://upload.wikimedia.org/wikipedia/commons/4/49/Sabal_causiarum.jpg','https://www.palmtalk.org/forum/uploads/monthly_2018_11/SCausiarum2018oct.jpg.bc6ca45cfdb0f0cac92d4808353ace90.jpg','https://www.plantdelights.com/cdn/shop/files/Sabal-palmarum-Just-Cause.i-16952.s-67775.r-1_008bdf0e-0afb-4761-85ef-b0e26e644630_600x.jpg?v=1765556599','https://www.palmtalk.org/forum/uploads/monthly_2023_10/IMG_9543.JPG.c48bfc59318457564b2b88f809254508.JPG']::text[], 'Sabal causiarum | Palmera de Sombrero de Puerto Rico', 'Compra Sabal causiarum, la majestuosa palmera de sombrero de Puerto Rico. Resistente, de tronco robusto y perfecta para climas mediterráneos. ¡Envíos a todos!', TRUE, FALSE, 0, 'Palmera de sombrero de Puerto Rico', 'palm', ARRAY['sol']::text[], ARRAY['tropical','subtropical','mediterráneo']::text[], -7, 'medium', 'medium', ARRAY['exterior','jardin']::text[], 'uncommon', 'easy', 'Es frecuentemente confundida con Sabal domingensis, pero S. causiarum tiene un tronco más masivo y liso. Confianza alta en identificación y datos de cultivo.', 'Arecaceae', 'Sabal causiarum palmera de tronco grueso', 'https://www.gbif.org/species/2731843', ARRAY['9a','9b','10a','10b','11a']::text[], NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET images=EXCLUDED.images, primary_image=EXCLUDED.primary_image, price=EXCLUDED.price, is_active=EXCLUDED.is_active;

INSERT INTO public.plants ("name", "scientific_name", "slug", "description", "short_description", "price", "stock_qty", "container_size", "growth_rate", "mature_height", "mature_width", "origin_country", "origin_region", "native_habitat", "care_instructions", "curious_facts", "specifications", "images", "meta_title", "meta_description", "is_active", "is_featured", "display_order", "common_name", "plant_type", "exposure", "climate_zones", "min_temp_c", "water", "humidity", "plant_use", "rarity", "difficulty", "notes", "family", "image_alt_text", "reference_url", "hardiness_zones", "product_images", "tags")
VALUES ('Syagrus romanzoffiana', 'Syagrus romanzoffiana', 'syagrus-romanzoffiana', 'La Syagrus romanzoffiana, comúnmente conocida como Palmera Pindó o Coco Plumoso, es una de las palmeras ornamentales más populares y elegantes para climas templados y cálidos. Se distingue por su estípite (tronco) grisáceo y liso, que puede alcanzar alturas considerables, coronado por un penacho de hojas pinnadas de un verde intenso con un aspecto plumoso y arqueado muy atractivo. Es una especie de crecimiento relativamente rápido comparada con otras palmeras.

En cuanto a sus cuidados, es una planta rústica y adaptable. Prefiere exposiciones a pleno sol para un desarrollo óptimo, aunque tolera la semisombra en su etapa juvenil. Requiere suelos bien drenados y, aunque es resistente a la sequía una vez establecida, agradece riegos regulares durante los meses de verano. Es importante vigilar las carencias de micronutrientes (como el manganeso) en suelos muy alcalinos, lo cual se manifiesta con hojas amarillentas o deformadas. Soporta heladas ligeras de hasta -7°C, lo que la hace ideal para jardines mediterráneos y zonas costeras.', 'Palmera elegante de aspecto plumoso y crecimiento rápido, ideal para climas mediterráneos y subtropicales.', 15, 2, '25-50 litros', 'fast', '10-15 m', '4-6 m', 'BR', 'Sudamérica oriental', 'Bosques y zonas abiertas de Sudamérica, principalmente en Brasil, Paraguay, Uruguay y el norte de Argentina.', '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, ARRAY['https://upload.wikimedia.org/wikipedia/commons/2/29/Starr_020617-0019_Syagrus_romanzoffiana.jpg','https://www.viriar.com/cdn/shop/files/2bc9bb19-51fe-473e-8ff7-c96882cea496.jpg?v=1744388185','https://www.gardenia.net/wp-content/uploads/2023/05/Syagrus-romanzoffiana.webp','https://fsus.ncbg.unc.edu/img/orig/userimg/userimg_276838.jpg']::text[], 'Syagrus romanzoffiana | Palmera Pindó de Exterior', 'Compra Syagrus romanzoffiana (Palmera Pindó). Una palmera elegante, de crecimiento rápido y resistente al frío moderado. Ideal para jardines y avenidas.', TRUE, FALSE, 0, 'Palmera Pindó', 'palm', ARRAY['sol','semisol']::text[], ARRAY['mediterráneo','subtropical','templado','oceánico']::text[], -7, 'medium', 'medium', ARRAY['exterior','jardin','maceta']::text[], 'common', 'easy', 'Especie muy común en paisajismo debido a su estética tropical y resistencia. Identificación 100% segura. Confianza alta en todos los parámetros técnicos.', 'Arecaceae', 'Syagrus romanzoffiana palmera pindó coco plumoso', 'https://www.gbif.org/species/2734500', ARRAY['9a','9b','10a','10b','11a']::text[], NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET images=EXCLUDED.images, primary_image=EXCLUDED.primary_image, price=EXCLUDED.price, is_active=EXCLUDED.is_active;

-- Categoria derivada de plant_type, igual que el resto del catalogo.
UPDATE public.plants p SET category_id=c.id FROM public.categories c
 WHERE p.category_id IS NULL AND c.slug = CASE p.plant_type::text
   WHEN 'palm' THEN 'palmeras' WHEN 'cycad' THEN 'cicadas'
   WHEN 'tree' THEN 'arboles-ornamentales' WHEN 'shrub' THEN 'arbustos-ornamentales'
   WHEN 'fern' THEN 'helechos-arboreos' WHEN 'grass' THEN 'bambus'
   WHEN 'succulent' THEN 'suculentas' ELSE NULL END;
