-- Semilla del catalogo de The Remainder.
-- Generado desde scripts/catalogo-recuperado.json. SQL plano: vale en cualquier Postgres.

BEGIN;

INSERT INTO public.plants ("care_instructions", "climate_zones", "common_name", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Suelo profundo drenado|Riego regular joven|Pleno sol|Evitar caliza"'::jsonb, ARRAY['atlantico','subtropical']::text[], 'Paraná pine', '0,8L', '"Piñones comestibles|Longeva|En peligro"'::jsonb, 'intermediate', ARRAY['sol']::text[], '2023', 'Medio', ARRAY['9a','9b','10a']::text[], 'medium', TRUE, FALSE, '30-40m', '8-12m', 'Conífera sudamericana de gran porte y copa en candelabro, ideal para jardines amplios y colecciones.', 'Araucaria angustifolia: conífera monumental', -8, 'Araucaria angustifolia', 'Bosques montanos subtropicales', 'Sus semillas eran un alimento básico de pueblos indígenas y su recolección marcaba ciclos sociales y rituales.', 'BR', 'Sur de Brasil', 'tree', ARRAY['exterior','colección']::text[], 28, 'rare', 'https://www.argentinaforestal.com/2019/11/04/araucaria-angustifolia-un-gigante-de-la-selva-misionera-que-se-encuentra-bajo-una-iniciativa-de-manejo-conservacion-y-mejora-en-el-inta/', 'Araucaria angustifolia', 'Conífera monumental sudamericana de porte único', 'araucaria-angustifolia', '{"soil":"ácido-drenado","wind":"media","growth":"medio"}'::jsonb, 3, 'medium', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "common_name", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Suelo fértil|Riego frecuente|Proteger heladas|Evitar sequía"'::jsonb, ARRAY['atlantico','subtropical']::text[], 'Bangalow palm', '1L', '"Crecimiento rápido|Muy ornamental"'::jsonb, 'intermediate', ARRAY['sol','semisol']::text[], '2024', 'Rápido', ARRAY['9b','10a','10b']::text[], 'high', TRUE, FALSE, '20-25m', '4-6m', 'Palmera de crecimiento rápido y tronco liso, perfecta para climas suaves con humedad.', 'Archontophoenix cunninghamiana, palmera elegante', -3, 'Archontophoenix cunninghamiana', 'Bosques húmedos y riberas', 'En algunos países se considera invasora por su alta capacidad de germinación en riberas.', 'AU', 'Queensland/NSW', 'palm', ARRAY['exterior','colección']::text[], 16, 'uncommon', 'https://www.palmpedia.net/wiki/Archontophoenix_cunninghamiana', 'Archontophoenix cunninghamiana', 'Palmera elegante y de rápido crecimiento', 'archontophoenix-cunninghamiana', '{"soil":"fértil-húmedo","wind":"baja","salt":"baja"}'::jsonb, 3, 'high', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "common_name", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Humedad constante|Suelo profundo|Sombra ligera joven"'::jsonb, ARRAY['tropical','montano']::text[], 'Hill areca nut', '0,8L', '"Palmera montana|Muy poco común"'::jsonb, 'advanced', ARRAY['semisol']::text[], '2025', 'Medio', ARRAY['10a','10b']::text[], 'high', TRUE, FALSE, '15-20m', '3-5m', 'Palmera tropical de montaña que requiere humedad ambiental y temperaturas suaves.', 'Bentinckia condapanna, palmera montana', 5, 'Bentinckia condapanna', 'Bosques montanos húmedos', 'Crece de forma natural en pendientes muy pronunciadas, donde pocas palmeras sobreviven.', 'IN', 'Ghats Occidentales', 'palm', ARRAY['exterior','colección']::text[], 55, 'rare', 'https://palmpedia.net/wiki/Bentinckia_condapanna', 'Burretiokentia condapanna', 'Palmera alta tropical de montaña', 'bentinckia-condapanna', '{"soil":"profundo-húmedo","wind":"media","growth":"medio"}'::jsonb, 1, 'high', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Suelo drenado|Riego moderado|Evitar frío prolongado"'::jsonb, ARRAY['tropical']::text[], '0,8L', '"Endémica NC|Rara en cultivo"'::jsonb, 'expert', ARRAY['semisol']::text[], '2025', 'Lento', ARRAY['10a','10b']::text[], 'medium', TRUE, FALSE, '8-12m', '3-4m', 'Palmera endémica de Nueva Caledonia, de cultivo delicado y muy apreciada.', 'Burretiokentia hapala, rareza de colección', 4, 'Burretiokentia hapala', 'Bosques húmedos y laderas', 'Forma parte de un linaje de palmeras casi exclusivo de Nueva Caledonia.', 'NC', 'Nueva Caledonia', 'palm', ARRAY['exterior','colección']::text[], 50, 'extremely_rare', 'https://www.monaconatureencyclopedia.com/burretiokentia-hapala-2/?lang=es', 'Burretiokentia hapala', 'Palmera rara de Nueva Caledonia', 'burretiokentia-hapala', '{"soil":"drenado","wind":"media","growth":"lento"}'::jsonb, 4, 'medium', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "common_name", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Riego alto|Suelo rico|Evitar frío|Semisombra"'::jsonb, ARRAY['tropical']::text[], 'Fishtail palm ', '0,8L', '"Hojas “cola de pez”|Tallos monocárpicos"'::jsonb, 'intermediate', ARRAY['semisol']::text[], '2024', 'Rápido', ARRAY['10a','10b','11']::text[], 'high', TRUE, FALSE, '10-15m', '4-6m', 'Palmera tropical multicaul de hojas tipo cola de pez; perfecta para ambientes cálidos y húmedos.', 'Caryota mitis, palmera cola de pez', 5, 'Caryota mitis', 'Selvas húmedas', 'Puede florecer durante varios años antes de que el tallo muera definitivamente.', 'TH', 'Sudeste asiático', 'palm', ARRAY['exterior','interior','colección']::text[], 12, 'common', 'https://www.oxygenatwork.com/en/post/caryota-mitis-1', 'Caryota mitis', 'Palmera tropical de hojas en forma de cola de pez', 'caryota-mitis', '{"soil":"rico-húmedo","habit":"multicaul","growth":"rápido"}'::jsonb, 2, 'high', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Semisombra|Suelo drenado|Riego moderado|Crecimiento lento"'::jsonb, ARRAY['subtropical']::text[], '0,8L', '"Cícada longeva|Aspecto prehistórico"'::jsonb, 'advanced', ARRAY['semisol']::text[], '2022', 'Lento', ARRAY['10a','10b']::text[], 'medium', TRUE, FALSE, '1-2m', '1-2m', 'Cícada de colección, muy longeva y de crecimiento lento; ideal en semisombra con drenaje.', 'Ceratozamia hildae, cícada mexicana rara', 2, 'Ceratozamia hildae', 'Bosques subtropicales', 'Fue descrita científicamente en el siglo XX, a pesar de su aspecto “prehistórico”.', 'MX', 'Querétaro/Sierra Gorda', 'other', ARRAY['exterior','colección']::text[], 65, 'very_rare', 'https://www.monaconatureencyclopedia.com/ceratozamia-hildae/?lang=es', 'Ceratozamia hildae', 'Cícada mexicana de crecimiento lento', 'ceratozamia-hildae', '{"soil":"drenado","growth":"lento","pot":"apta"}'::jsonb, 1, 'medium', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "common_name", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "variety", "water", "weight_grams")
VALUES ('"Sombra luminosa|Riego moderado|Evitar sol fuerte"'::jsonb, ARRAY['interior','tropical']::text[], 'Palma de salón', '0,8L', '"Muy usada en interior|Resistente"'::jsonb, 'beginner', ARRAY['semisombra','sombra']::text[], '2025', 'Lento', ARRAY['10a','10b']::text[], 'medium', TRUE, FALSE, '2-3m', '1-2m', 'Palmera compacta para interior o semisombra, fácil y muy decorativa.', 'Chamaedorea elegans, palma de salón', 5, 'Chamaedorea elegans', 'Sotobosque tropical', 'Fue una de las primeras palmeras exportadas masivamente a Europa en el siglo XIX.', 'MX', 'Veracruz/Chiapas', 'palm', ARRAY['interior','exterior','colección']::text[], 15, 'common', 'https://www.picturethisai.com/es/wiki/Chamaedorea_elegans__Negrita_.html', 'Chamaedorea elegans', 'Palmera compacta ideal para interior', 'chamaedorea-elegans-negrita', '{"soil":"ligero","light":"interior","growth":"lento"}'::jsonb, 3, '"Negrita"', 'medium', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "common_name", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Semisombra|Suelo húmedo|Tolera frío moderado"'::jsonb, ARRAY['atlantico','subtropical']::text[], 'Palma bambú ', '0,8L', '"Buena para climas suaves|Frutos rojos"'::jsonb, 'intermediate', ARRAY['semisombra']::text[], '2024', 'Medio', ARRAY['8b','9a','9b']::text[], 'medium', TRUE, FALSE, '3-4m', '1-2m', 'Palmera de sombra con buena tolerancia al frío moderado, ideal para jardines templados.', 'Chamaedorea microspadix resistente', -6, 'Chamaedorea microspadix', 'Bosques montanos', 'Produce frutos rojos muy decorativos que atraen fauna en su hábitat natural.', 'MX', 'Sierra Madre', 'palm', ARRAY['exterior','colección']::text[], 18, 'uncommon', 'https://www.argentinat.org/taxa/206171-Chamaedorea-microspadix', 'Chamaedorea microspadix', 'Palmera resistente para sombra', 'chamaedorea-microspadix', '{"soil":"húmedo","cold":"alta","habit":"multicaul"}'::jsonb, 3, 'medium', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Suelo drenado|Riego moderado|Tolera frío"'::jsonb, ARRAY['atlantico','subtropical']::text[], '0,8L', '"Muy rústica|Versátil"'::jsonb, 'intermediate', ARRAY['sol','semisol']::text[], '2024', 'Medio', ARRAY['8a','8b','9a']::text[], 'medium', TRUE, FALSE, '2-4m', '1-2m', 'Palmera compacta y muy rústica, tolera frío y se adapta bien con riego moderado.', 'Chamaedorea radicalis rústica', -9, 'Chamaedorea radicalis', 'Laderas y bosques secos-subhúmedos', 'Puede florecer incluso sin desarrollar un tronco visible.', 'MX', 'Nuevo León/Tamaulipas', 'palm', ARRAY['exterior','colección']::text[], 18, 'uncommon', 'https://identify.plantnet.org/es/k-world-flora/species/Chamaedorea%20radicalis%20Mart./data', 'Chamaedorea radicalis', 'Palmera rústica tolerante al frío', 'chamaedorea-radicalis', '{"soil":"drenado","cold":"muy alta","growth":"medio"}'::jsonb, 4, 'medium', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "common_name", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Sombra|Humedad alta|Suelo rico|Riego frecuente"'::jsonb, ARRAY['tropical']::text[], 'Tepejilote', '0,8L', '"Uso alimentario tradicional"'::jsonb, 'advanced', ARRAY['sombra','semisombra']::text[], '2024', 'Medio', ARRAY['10a','10b']::text[], 'high', TRUE, FALSE, '4-6m', '2-3m', 'Palmera de sotobosque tropical; requiere humedad constante y sombra.', 'Chamaedorea tepejilote tropical', 6, 'Chamaedorea tepejilote', 'Selva húmeda', 'Sus inflorescencias aún se consumen como manjar estacional en mercados locales.', 'GT', 'Centroamérica', 'palm', ARRAY['exterior','colección']::text[], 18, 'uncommon', 'https://www.inecol.mx/index.php/divulgacion/ciencia-hoy/tepejilote-maiz-de-montana-una-palma-asombrosa', 'Chamaedorea tepejilote', 'Palmera tropical de sotobosque', 'chamaedorea-tepejilote', '{"soil":"rico-húmedo","light":"sombra","growth":"medio"}'::jsonb, 3, 'high', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "variety", "water", "weight_grams")
VALUES ('"Suelo drenado|Riego moderado|Clima suave"'::jsonb, ARRAY['subtropical','tropical']::text[], '0,8L', '"Brotes jóvenes llamativos"'::jsonb, 'advanced', ARRAY['semisol']::text[], '2024', 'Medio', ARRAY['10a','10b']::text[], 'medium', TRUE, FALSE, '12-18m', '4-6m', 'Palmera de colección de follaje elegante, ideal en semisol con riego regular.', 'Chambeyronia lepidota, palmera ornamental', 0, 'Chambeyronia lepidota', 'Bosques húmedos', 'Está emparentada con especies famosas por sus hojas jóvenes de colores intensos.', 'NC', 'Nueva Caledonia', 'palm', ARRAY['exterior','colección']::text[], 45, 'rare', 'https://www.palmpedia.net/wiki/Chambeyronia_lepidota', 'Chambeyronia lepidota', 'Palmera ornamental de follaje elegante', 'chambeyronia-lepidota-mid-elevation', '{"soil":"drenado","feature":"brotes color","growth":"medio"}'::jsonb, 1, '"Mid elevation"', 'medium', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "common_name", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Suelo drenado|Humedad ambiental|Evitar frío"'::jsonb, ARRAY['tropical']::text[], 'Lifou palm', '0,8L', '"Endémica|Muy rara"'::jsonb, 'expert', ARRAY['semisol']::text[], '2025', 'Lento', ARRAY['10a','10b']::text[], 'medium', TRUE, FALSE, '10-15m', '3-5m', 'Palmera endémica muy rara, de crecimiento lento y gran valor ornamental.', 'Cyphophoenix nucele, rareza NC', 3, 'Cyphophoenix nucele', 'Bosques insulares', 'Su nombre hace referencia a la textura escamosa de sus semillas.', 'NC', 'Islas Loyauté', 'palm', ARRAY['exterior','colección']::text[], 64, 'extremely_rare', 'https://palmpedia.net/wiki/Cyphophoenix_nucele', 'Cyphophoenix nucele', 'Palmera rara endémica de Nueva Caledonia', 'cyphophoenix-nucele', '{"soil":"drenado","growth":"lento","salt":"media"}'::jsonb, 1, 'medium', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Humedad alta|Viento protegido|Suelo profundo"'::jsonb, ARRAY['tropical','oceanico']::text[], '0,8L', '"Porte muy elegante|Insular"'::jsonb, 'advanced', ARRAY['semisol']::text[], '2025', 'Medio', ARRAY['10a','10b']::text[], 'high', TRUE, FALSE, '12-20m', '3-5m', 'Palmera oceánica muy ornamental; prefiere humedad constante y abrigo del viento.', 'Dictyocaryum lamarckianum esbelta', 2, 'Dictyocaryum lamarckianum', 'Bosques húmedos oceánicos', 'Fue nombrada en honor a Lamarck, uno de los pioneros de la botánica evolutiva.', 'MU', 'Mascareñas', 'palm', ARRAY['exterior','colección']::text[], 55, 'very_rare', 'https://www.naturalista.uy/taxa/365207-Dictyocaryum-lamarckianum', 'Dictyosperma lamarckianum', 'Palmera tropical esbelta y muy ornamental', 'dictyocaryum-lamarckianum', '{"soil":"profundo-húmedo","wind":"baja","growth":"medio"}'::jsonb, 1, 'high', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "common_name", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "variety", "water", "weight_grams")
VALUES ('"Suelo drenado|Poco riego|Sol|Evitar encharque"'::jsonb, ARRAY['mediterraneo','subtropical']::text[], 'Drago', '1L', '"“Sangre de drago”|Muy longeva"'::jsonb, 'beginner', ARRAY['sol']::text[], '2025', 'Lento', ARRAY['9a','9b','10a']::text[], 'low', TRUE, FALSE, '10-15m', '6-10m', 'Árbol icónico y escultórico, muy resistente a sequía en climas suaves.', 'Dracaena draco, drago canario', -3, 'Dracaena draco', 'Laderas secas y roquedos', 'La resina rojiza fue usada históricamente como pigmento y barniz para instrumentos.', 'ES', 'Canarias/Macaronesia', 'tree', ARRAY['exterior','colección']::text[], 17, 'uncommon', 'https://jardinpostal.com/dracaena-draco-drago-de-canarias-cuidados-y-caracteristicas/?srsltid=AfmBOoqgoME3RXsnv3J2uJLSTMzwNEd0DB22skguZTvK7eZk53BUpJn-', 'Dracaena draco', 'Árbol icónico de porte escultórico', 'dracaena-draco-madeira', '{"soil":"mineral","drought":"alta","growth":"lento"}'::jsonb, 4, '"Madeira"', 'low', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Suelo mineral|Riego mínimo|Mucha luz"'::jsonb, ARRAY['mediterraneo','tropical']::text[], '0,3L', '"Formas escultóricas|Endémica"'::jsonb, 'advanced', ARRAY['sol']::text[], '2018', 'Lento', ARRAY['10a','10b']::text[], 'low', TRUE, FALSE, '1-2m', '1-2m', 'Suculenta de colección, requiere mucha luz y riegos muy espaciados.', 'Euphorbia francoisii suculenta rara', 8, 'Euphorbia francoisii', 'Matorral seco espinoso', 'Presenta una enorme variabilidad de formas incluso dentro de la misma población.', 'MG', 'Madagascar', 'succulent', ARRAY['interior','colección']::text[], 65, 'very_rare', 'https://www.littleoneplantnursery.com/know/categories/euphorbia-francoisii', 'Euphorbia francoisii', 'Suculenta exótica y escultural', 'euphorbia-francoisii', '{"soil":"muy drenante","water":"muy bajo","spines":"sí"}'::jsonb, 3, 'low', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Suelo ácido|Humedad alta|Semisol|Riego regular"'::jsonb, ARRAY['tropical']::text[], '0,8L', '"Floración ornamental|Poco común"'::jsonb, 'advanced', ARRAY['semisol']::text[], '2025', 'Medio', ARRAY['10a','10b']::text[], 'high', TRUE, FALSE, '3-5m', '2-3m', 'Arbusto tropical de floración decorativa; necesita humedad ambiental y suelo ácido.', 'Ixora margaretae tropical ornamental', 7, 'Ixora margaretae', 'Bosque tropical húmedo', 'Pertenece a un género muy conocido, pero esta especie es casi desconocida fuera de su isla.', 'NC', 'Nueva Caledonia', 'other', ARRAY['exterior','interior','colección']::text[], 25, 'rare', 'https://identify.plantnet.org/es/k-world-flora/species/Ixora%20margaretae%20(N.Hall%C3%A9)%20Mouly%20&%20B.Bremer/data', 'Oxera margaretae', 'Arbusto tropical de floración ornamental', 'ixora-margaretae', '{"soil":"ácido","humidity":"alta","flower":"ornamental"}'::jsonb, 3, 'high', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "common_name", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Sol|Riego bajo adulto|Suelo drenado"'::jsonb, ARRAY['mediterraneo','subtropical']::text[], 'Ribbon fan palm', '0,8L', '"Muy tolerante a sequía"'::jsonb, 'intermediate', ARRAY['sol']::text[], '2024', 'Medio', ARRAY['9a','9b','10a']::text[], 'low', TRUE, FALSE, '10-15m', '4-6m', 'Palmera de hojas palmadas muy resistente y adaptable, ideal para sol y bajo riego.', 'Livistona decipiens, abanico resistente', -6, 'Livistona decora', 'Bosques abiertos/secos', 'Sus hojas pueden producir sonidos audibles con viento fuerte.', 'AU', 'Queensland', 'palm', ARRAY['exterior','colección']::text[], 10, 'common', 'https://palmpedia.net/wiki/Livistona_decora', 'Livistona decipiens', 'Palmera resistente de hojas palmadas', 'livistona-decora', '{"soil":"drenado","drought":"alta","growth":"medio"}'::jsonb, 7, 'low', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "common_name", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Humedad alta|Semisol|Suelo drenado"'::jsonb, ARRAY['tropical']::text[], 'Dothalu palm', '0,8L', '"Crece en roquedos"'::jsonb, 'expert', ARRAY['semisol']::text[], '2025', 'Lento', ARRAY['10a','10b']::text[], 'high', TRUE, FALSE, '10-15m', '4-6m', 'Palmera muy rara de Sri Lanka, amante de humedad y semisombra.', 'Loxococcus rupicola, palmera rarísima', 4, 'Loxococcus rupicola', 'Rocas húmedas y bosques', 'Es una de las pocas palmeras adaptadas a crecer directamente sobre roca.', 'LK', 'Sri Lanka', 'palm', ARRAY['exterior','colección']::text[], 52, 'extremely_rare', 'https://www.palmpedia.net/wiki/Loxococcus_rupicola', 'Loxococcus rupicola', 'Palmera tropical poco común', 'loxococcus-rupicola', '{"soil":"drenado-húmedo","habitat":"rocoso","growth":"lento"}'::jsonb, 1, 'high', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Suelo ácido|Riego regular|Proteger vientos fríos"'::jsonb, ARRAY['atlantico','templado']::text[], '1L', '"Floración muy temprana"'::jsonb, 'advanced', ARRAY['sol','semisol']::text[], '2024', 'Medio', ARRAY['7b','8a','8b']::text[], 'medium', TRUE, FALSE, '20-25m', '8-12m', 'Magnolia de gran porte y floración temprana; ideal en climas frescos y suelos ácidos.', 'Magnolia campbellii, floración espectacular', -12, 'Magnolia campbellii', 'Bosques templados montanos', 'Florece antes de que broten las hojas, creando un impacto visual muy marcado.', 'NP', 'Himalaya', 'tree', ARRAY['exterior','colección']::text[], 15, 'uncommon', 'https://www.treesandshrubsonline.org/articles/magnolia/magnolia-campbellii/', 'Magnolia campbellii', 'Magnolia de gran floración primaveral', 'magnolia-campbellii', '{"soil":"ácido","flower":"muy grande","growth":"medio"}'::jsonb, 2, 'medium', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Suelo profundo|Riego regular|Sol o semisol"'::jsonb, ARRAY['mediterraneo','subtropical']::text[], '0,8L', '"Flores aromáticas|Perenne"'::jsonb, 'intermediate', ARRAY['sol','semisol']::text[], '2024', 'Medio', ARRAY['8a','8b','9a','9b']::text[], 'medium', TRUE, FALSE, '20-30m', '8-12m', 'Árbol perenne con grandes flores blancas; resistente y muy ornamental en jardines.', 'Magnolia grandiflora, flores aromáticas', -10, 'Magnolia grandiflora', 'Bosques subtropicales', 'Sus flores pueden tardar más de un mes en descomponerse tras caer.', 'US', 'SE Estados Unidos', 'tree', ARRAY['exterior']::text[], 7, 'common', 'https://www.treesandshrubsonline.org/articles/magnolia/magnolia-grandiflora/', 'Magnolia grandiflora', 'Árbol perenne de flores blancas aromáticas', 'magnolia-grandiflora', '{"soil":"profundo","evergreen":"sí","flower":"aromática"}'::jsonb, 10, 'medium', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Semisol|Suelo ácido|Riego moderado"'::jsonb, ARRAY['subtropical']::text[], '0,8L', '"Muy aromática|Compacta"'::jsonb, 'intermediate', ARRAY['semisol']::text[], '2024', 'Lento', ARRAY['8b','9a','9b']::text[], 'medium', TRUE, FALSE, '6-10m', '3-5m', 'Magnolia compacta y perfumada; ideal en semisol con suelos ácidos y riego regular.', 'Magnolia laevifolia compacta aromática', -5, 'Magnolia laevifolia', 'Bosques subtropicales', 'Durante años se clasificó en otro género por diferencias florales.', 'CN', 'Yunnan/SE Asia', 'tree', ARRAY['exterior','colección']::text[], 22, 'uncommon', 'https://www.treesandshrubsonline.org/articles/magnolia/magnolia-laevifolia/', 'Magnolia laevifolia', 'Magnolia compacta y aromática', 'magnolia-laevifolia', '{"soil":"ácido","size":"compacta","flower":"perfumada"}'::jsonb, 1, 'medium', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "common_name", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Pleno sol|Riego bajo|Suelo drenado"'::jsonb, ARRAY['mediterraneo','subtropical']::text[], 'Palmera canaria', '0,8L', '"Palmera icónica | Muy robusta"'::jsonb, 'beginner', ARRAY['sol']::text[], '2023', 'Medio', ARRAY['9a','9b','10a']::text[], 'low', TRUE, FALSE, '15-20m', '6-10m', 'Palmera muy resistente y ornamental, perfecta para sol y bajo mantenimiento.', 'Phoenix canariensis, palmera canaria', -6, 'Phoenix canariensis', 'Barrancos y zonas secas', 'Es una de las palmeras más trasplantadas del mundo en estado adulto.', 'ES', 'Islas Canarias', 'palm', ARRAY['exterior']::text[], 7, 'common', 'https://www.consultaplantas.com/index.php/es/plantas-por-nombre/plantas-de-la-m-a-la-r/3377-cuidados-de-la-planta-phoenix-canariensis-o-palma-canaria', 'Phoenix canariensis', 'Palmera emblemática y muy resistente', 'phoenix-canariensis', '{"soil":"drenado","drought":"alta","salt":"media"}'::jsonb, 3, 'low', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "common_name", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "variety", "water", "weight_grams")
VALUES ('"Mucho sol|Riego bajo|Suelo drenado"'::jsonb, ARRAY['arido','mediterraneo']::text[], 'Palmera datilera', '0,8L', '"Produce dátiles | Muy longeva"'::jsonb, 'intermediate', ARRAY['sol']::text[], '2023', 'Medio', ARRAY['9a','9b','10a']::text[], 'low', TRUE, FALSE, '15-25m', '6-10m', 'Palmera del desierto, muy resistente al calor; requiere sol y drenaje excelente.', 'Phoenix dactylifera, palmera datilera', -7, 'Phoenix dactylifera', 'Oasis y zonas áridas', 'Existen miles de cultivares tradicionales con usos muy específicos.', 'MA', 'N. África/Oriente Medio', 'palm', ARRAY['exterior','colección']::text[], 7, 'common', 'https://www.arbolapp.es/especies/ficha/phoenix-dactylifera/', 'Phoenix dactylifera', 'Palmera datilera de gran porte', 'phoenix-dactylifera-medjool', '{"soil":"arenoso-drenado","drought":"muy alta","fruit":"dátiles"}'::jsonb, 1, '"Medjool"', 'low', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "common_name", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Resiste viento|Riego moderado|Suelo drenado"'::jsonb, ARRAY['atlantico','oceanico']::text[], 'Wharariki', '0,8L', '"Uso tradicional fibra | Muy rústica"'::jsonb, 'beginner', ARRAY['sol','semisol']::text[], '2025', 'Medio', ARRAY['8a','8b','9a','9b']::text[], 'medium', TRUE, FALSE, '2-4m', '2-3m', 'Planta estructural resistente al viento; ideal en climas oceánicos con riego moderado.', 'Phormium cookianum, wharariki resistente', -8, 'Phormium cookianum', 'Costas ventosas y laderas', 'Sus fibras se usaron históricamente para fabricar cuerdas y tejidos resistentes al agua.', 'NZ', 'Nueva Zelanda', 'grass', ARRAY['exterior']::text[], 12, 'common', 'https://www.verdeesvida.es/fichas_de_plantas/arbustos-y-trepadoras_1/lino-de-nueva-zelanda--formio_3122', 'Phormium cookianum', 'Planta estructural de hojas largas', 'phormium-cookianum', '{"wind":"alta","salt":"media","habit":"macollo"}'::jsonb, 10, 'medium', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "common_name", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Semisol|Riego moderado|Poda tolerada"'::jsonb, ARRAY['subtropical','atlantico']::text[], 'Buddhist pine', '1L', '"Muy usado en bonsái"'::jsonb, 'beginner', ARRAY['semisol','sombra']::text[], '2024', 'Lento', ARRAY['8a','8b','9a','9b']::text[], 'medium', TRUE, FALSE, '10-20m', '4-8m', 'Conífera ornamental muy versátil, apta para setos, arbolado y bonsái.', 'Podocarpus macrophyllus, pino budista', -10, 'Podocarpus macrophyllus', 'Bosques templados-subtropicales', 'No es un pino real, aunque su nombre común lo sugiera.', 'JP', 'Japón/China', 'tree', ARRAY['exterior','interior','colección']::text[], 18, 'common', 'https://identify.plantnet.org/es/k-world-flora/species/Podocarpus%20macrophyllus%20(Thunb.)%20Sweet/data', 'Podocarpus macrophyllus', 'Conífera ornamental muy versátil', 'podocarpus-macrophyllus', '{"pruning":"alta","shade":"media","use":"seto/bonsái"}'::jsonb, 3, 'medium', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "common_name", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Semisol|Suelo drenado|Riego moderado"'::jsonb, ARRAY['tropical','oceanico']::text[], 'Loulu', '0,8L', '"“Loulu” hawaiana | Protegida"'::jsonb, 'advanced', ARRAY['semisol']::text[], '2024', 'Lento', ARRAY['10a','10b']::text[], 'medium', TRUE, FALSE, '8-12m', '3-5m', 'Palmera hawaiana rara de hojas circulares, ideal en climas cálidos sin heladas.', 'Pritchardia hillebrandii, loulu hawaiana', 4, 'Pritchardia hillebrandii', 'Bosques húmedos insulares', 'Forma parte de un grupo de palmeras con fuerte valor cultural en Hawái.', 'US', 'Hawái', 'palm', ARRAY['exterior','colección']::text[], 25, 'extremely_rare', 'https://www.palmpedia.net/wiki/Pritchardia_hillebrandii', 'Pritchardia hillebrandii', 'Palmera hawaiana de hojas circulares', 'pritchardia-hillebrandii', '{"soil":"drenado","salt":"baja","growth":"lento"}'::jsonb, 1, 'medium', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "common_name", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Riego regular|Suelo drenado|Clima cálido"'::jsonb, ARRAY['tropical']::text[], 'Solitaire palm', '0,8L', '"Crece rápido"'::jsonb, 'intermediate', ARRAY['sol','semisol']::text[], '2024', 'Rápido', ARRAY['10a','10b']::text[], 'medium', TRUE, FALSE, '10-12m', '3-4m', 'Palmera estilizada y rápida, perfecta para dar verticalidad en jardines cálidos.', 'Ptychosperma elegans, palmera estilizada', 5, 'Ptychosperma elegans', 'Bosques tropicales', 'Es una de las palmeras tropicales más usadas en paisajismo urbano asiático.', 'AU', 'Queensland', 'palm', ARRAY['exterior','colección']::text[], 40, 'common', 'https://www.palmpedia.net/palmsforcal/Ptychosperma_elegans', 'Ptychosperma elegans', 'Palmera estilizada de crecimiento rápido', 'ptychosperma-elegans', '{"growth":"rápido","soil":"drenado","habit":"solitaria"}'::jsonb, 1, 'medium', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Sol|Suelo profundo|Riego moderado joven"'::jsonb, ARRAY['atlantico','continental']::text[], '1L', '"Muy longevo | Gran valor ecológico"'::jsonb, 'beginner', ARRAY['sol']::text[], '2024', 'Medio', ARRAY['7a','7b','8a','8b','9a']::text[], 'medium', TRUE, FALSE, '15-30m', '10-20m', 'Árbol robusto y longevo del género Quercus; aporta sombra y alto valor ecológico.', 'Quercus, roble/encina para jardín', -15, 'Quercus sp.', 'Bosques templados', 'Algunas especies del género pueden rebrotar tras incendios severos.', 'ES', 'Europa/Asia/América', 'tree', ARRAY['exterior']::text[], 5, 'common', 'Quercus sp.', 'Árbol robusto y longevo', 'quercus-sp', '{"soil":"profundo","wildlife":"alto","growth":"medio"}'::jsonb, 3, 'medium', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "common_name", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "variety", "water", "weight_grams")
VALUES ('"Suelo profundo|Riego moderado|Clima suave"'::jsonb, ARRAY['oceanico']::text[], 'Norfolk Island palm', '0,8L', '"Endémica Norfolk | Muy elegante"'::jsonb, 'advanced', ARRAY['semisol']::text[], '2025', 'Lento', ARRAY['10a','10b']::text[], 'medium', TRUE, FALSE, '10-15m', '3-5m', 'Palmera oceánica elegante y rara; necesita clima suave, humedad moderada y suelo profundo.', 'Rhopalostylis baueri, palmera de Norfolk', 0, 'Rhopalostylis baueri', 'Bosques oceánicos', 'Crece de forma natural en suelos volcánicos profundos.', 'NF', 'Norfolk Island', 'palm', ARRAY['exterior','colección']::text[], 38, 'very_rare', 'https://www.palmpedia.net/wiki/Rhopalostylis_baueri', 'Rhopalostylis baueri', 'Palmera elegante de clima oceánico', 'rhopalostylis-baueri-var-cheesemanii', '{"soil":"profundo","wind":"baja","growth":"lento"}'::jsonb, 2, 'var. cheesemanii', 'medium', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "common_name", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "variety", "water", "weight_grams")
VALUES ('"Semisol|Suelo húmedo|Proteger heladas fuertes"'::jsonb, ARRAY['atlantico','oceanico']::text[], 'Nīkau', '0,8L', '"Nīkau | Emblemática"'::jsonb, 'advanced', ARRAY['semisol']::text[], '2025', 'Lento', ARRAY['9a','9b','10a']::text[], 'medium', TRUE, FALSE, '12-15m', '3-5m', 'Palmera nativa de NZ, muy ornamental; prefiere suelos húmedos y clima oceánico.', 'Rhopalostylis sapida, nīkau de NZ', -4, 'Rhopalostylis sapida', 'Bosques oceánicos templados', 'Es la palmera más austral del planeta en su distribución natural.', 'NZ', 'Nueva Zelanda', 'palm', ARRAY['exterior','colección']::text[], 38, 'uncommon', 'https://palmpedia.net/wiki/Rhopalostylis_sapida', 'Rhopalostylis sapida', 'Palmera nativa de Nueva Zelanda', 'rhopalostylis-sapida-var-oceana', '{"soil":"húmedo","cold":"media","growth":"lento"}'::jsonb, 1, 'var. oceana', 'medium', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "common_name", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Sol|Riego bajo|Suelo drenado"'::jsonb, ARRAY['subtropical']::text[], 'Miami palmetto', '0,8L', '"Extinta en hábitat"'::jsonb, 'advanced', ARRAY['sol']::text[], '2025', 'Lento', ARRAY['10a','10b']::text[], 'low', TRUE, FALSE, '6-8m', '3-4m', 'Palmera extremadamente rara; resistente y de bajo riego, pieza de colección excepcional.', 'Sabal miamiensis, palmera extinta en hábitat', -3, 'Sabal miamiensis', 'Matorral/pinar subtropical', 'Solo se conoce por registros históricos y cultivo ex situ.', 'US', 'Florida (Miami-Dade)', 'palm', ARRAY['exterior','colección']::text[], 37, 'extremely_rare', 'https://www.palmpedia.net/wiki/Sabal_miamiensis', 'Sabal miamiensis', 'Palmera extremadamente rara', 'sabal-miamiensis', '{"soil":"drenado","drought":"alta","status":"extinta silvestre"}'::jsonb, 3, 'low', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "common_name", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "variety", "water", "weight_grams")
VALUES ('"Sol|Bajo riego|Tolera salinidad"'::jsonb, ARRAY['subtropical','mediterraneo']::text[], 'Cabbage palmetto', '0,8L', '"Muy resistente a viento/sal"'::jsonb, 'beginner', ARRAY['sol']::text[], '2025', 'Medio', ARRAY['9a','9b','10a']::text[], 'low', TRUE, FALSE, '15-20m', '4-6m', 'Palmera muy resistente al viento y la sal; excelente para jardines costeros.', 'Sabal palmetto, resistente al viento', -10, 'Sabal palmetto', 'Costas y marismas', 'Puede sobrevivir a huracanes que derriban árboles de mayor porte.', 'US', 'SE EE. UU.', 'palm', ARRAY['exterior']::text[], 18, 'common', 'https://palmpedia.net/wiki/Sabal_sp._%27Lisa%27', 'Sabal palmetto', 'Palmera resistente al viento y la sal', 'sabal-palmetto-lisa', '{"salt":"alta","wind":"alta","drought":"alta"}'::jsonb, 1, '"Lisa"', 'low', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Semisol|Riego moderado-alto|Humedad ambiental"'::jsonb, ARRAY['tropical']::text[], '0,8L', '"Follaje exótico"'::jsonb, 'advanced', ARRAY['semisol','sombra']::text[], '2025', 'Medio', ARRAY['10a','10b']::text[], 'high', TRUE, FALSE, '4-6m', '3-4m', 'Arbusto tropical de hojas compuestas; ideal con humedad ambiental y luz filtrada.', 'Schefflera pueckleri, follaje exótico', 6, 'Heptapleurum calyptratum', 'Bosques tropicales', 'Su follaje recuerda a estructuras radiales muy comunes en la familia Araliaceae.', 'TZ', 'África tropical', 'other', ARRAY['interior','exterior','colección']::text[], 15, 'rare', 'https://identify.plantnet.org/es/useful/species/Schefflera%20pueckleri%20(K.Koch)%20Frodin/data', 'Schefflera pueckleri', 'Arbusto tropical de follaje exótico', 'heptapleurum-calyptratum', '{"humidity":"alta","indoor":"sí","growth":"medio"}'::jsonb, 1, 'high', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Sol|Riego moderado|Suelo drenado"'::jsonb, ARRAY['tropical','seco']::text[], '0,8L', '"Endémica de Ceará"'::jsonb, 'intermediate', ARRAY['sol']::text[], '2025', 'Medio', ARRAY['10a','10b']::text[], 'medium', TRUE, FALSE, '8-12m', '3-5m', 'Palmera brasileña poco común; aprecia sol y drenaje con riego moderado.', 'Syagrus cearensis, palmera brasileña rara', -2, 'Syagrus cearensis', 'Bosques secos/caatinga', 'Adaptada a climas con fuertes contrastes entre estación seca y lluviosa.', 'BR', 'Ceará', 'palm', ARRAY['exterior','colección']::text[], 29, 'uncommon', 'https://palmpedia.net/wiki/Syagrus_cearensis', 'Syagrus cearensis', 'Palmera brasileña poco común', 'syagrus-cearensis', '{"soil":"drenado","drought":"media","growth":"medio"}'::jsonb, 1, 'medium', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "common_name", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Drenaje alto|Riego moderado|Tolera frío"'::jsonb, ARRAY['atlantico','templado']::text[], 'Dwarf windmill palm', '0,8L', '"Palmera enana | Muy rústica"'::jsonb, 'intermediate', ARRAY['sol','semisol']::text[], '2023', 'Lento', ARRAY['7b','8a','8b']::text[], 'medium', TRUE, FALSE, '1-2m', '1-2m', 'Palmera enana de colección, muy resistente al frío y perfecta para espacios pequeños.', 'Trachycarpus nanus, palmera enana rústica', -12, 'Trachycarpus nanus', 'Laderas rocosas montanas', 'Apenas desarrolla tronco visible incluso en ejemplares muy viejos.', 'CN', 'China', 'palm', ARRAY['exterior','colección']::text[], 30, 'rare', 'https://www.palmpedia.net/wiki/Trachycarpus_nanus', 'Trachycarpus nanus', 'Palmera enana muy resistente al frío', 'trachycarpus-nanus', '{"cold":"muy alta","habit":"multicaul","soil":"drenado"}'::jsonb, 1, 'medium', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "common_name", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "variety", "water", "weight_grams")
VALUES ('"Sol|Suelo drenado|Tolera frío"'::jsonb, ARRAY['atlantico','templado']::text[], 'Stone Gate palm', '0,8L', '"Envés plateado"'::jsonb, 'intermediate', ARRAY['sol']::text[], '2023', 'Medio', ARRAY['7b','8a','8b']::text[], 'medium', TRUE, FALSE, '8-12m', '3-5m', 'Palmera muy ornamental de hojas plateadas, resistente al frío y amante del drenaje.', 'Trachycarpus princeps, Stone Gate palm', -12, 'Trachycarpus princeps', 'Acantilados calizos', 'Fue descubierta en acantilados casi inaccesibles del sur de China.', 'CN', 'Yunnan', 'palm', ARRAY['exterior','colección']::text[], 35, 'rare', 'https://www.palmpedia.net/wiki/Trachycarpus_princeps', 'Trachycarpus princeps', 'Palmera de hojas plateadas', 'trachycarpus-princeps-stone-gate', '{"feature":"envés plateado","soil":"calizo-drenado","cold":"alta"}'::jsonb, 1, '"Stone Gate"', 'medium', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "variety", "water", "weight_grams")
VALUES ('"Sol/semisol|Suelo drenado|Riego moderado"'::jsonb, ARRAY['atlantico','templado']::text[], '0,8L', '"Depende del clon/especie"'::jsonb, 'beginner', ARRAY['sol','semisol']::text[], '2023', 'Medio', ARRAY['8a','8b','9a']::text[], 'medium', TRUE, FALSE, '6-12m', '3-5m', 'Trachycarpus de clima templado, resistente al frío; ideal para exterior con buen drenaje.', 'Trachycarpus sp., palmera rústica', -10, 'Trachycarpus sp.', 'Montano templado', 'Muchas formas en cultivo aún no están formalmente descritas.', 'CN', 'Asia', 'palm', ARRAY['exterior','colección']::text[], 50, 'uncommon', 'Trachycarpus sp.', 'Palmera rústica de clima templado', 'trachycarpus-sp-himgarda', '{"note":"requiere identificación","cold":"alta","growth":"medio"}'::jsonb, 1, '"Himgarda"', 'medium', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Sol|Soporte/trepa|Riego regular"'::jsonb, ARRAY['atlantico','templado']::text[], '1L', '"Trepadora poco común"'::jsonb, 'beginner', ARRAY['sol']::text[], '2026', 'Rápido', ARRAY['8a','8b','9a']::text[], 'medium', TRUE, FALSE, 'Trepadora', '3-6m', 'Trepadora vigorosa para pérgolas y muros; agradece sol y riego regular en crecimiento.', 'Vitis cognitae, trepadora ornamental', -12, 'Vitis cognitae', 'Bosque templado húmedo', 'Produce zarcillos extremadamente fuertes para su tamaño.', 'CN', 'Asia oriental', 'other', ARRAY['exterior']::text[], 18, 'uncommon', 'https://lexiplant.com/es/plant/vitis-coignetiae-crimson-glory-vine', 'Vitis cognitae', 'Trepadora vigorosa ornamental', 'vitis-cognitae', '{"habit":"trepadora","support":"sí","growth":"rápido"}'::jsonb, 1, 'medium', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "common_name", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "water", "weight_grams")
VALUES ('"Sombra|Humedad alta|Suelo rico"'::jsonb, ARRAY['tropical','montano']::text[], 'Thakal', '1L', '"Hojas en dos planos"'::jsonb, 'advanced', ARRAY['semisombra']::text[], '2025', 'Medio', ARRAY['10a','10b']::text[], 'high', TRUE, FALSE, '6-8m', '3-5m', 'Palmera tropical de hojas en dos planos; ideal en sombra húmeda y suelos ricos.', 'Wallichia disticha, palmera arquitectónica', 2, 'Wallichia disticha', 'Bosques húmedos montanos', 'Su disposición foliar en dos planos es muy poco común en palmeras.', 'BT', 'Himalaya oriental/SE Asia', 'palm', ARRAY['exterior','colección']::text[], 32, 'rare', 'https://www.monaconatureencyclopedia.com/wallichia-disticha/?lang=es', 'Wallichia disticha', 'Palmera tropical de hojas en dos planos', 'wallichia-disticha', '{"feature":"disticha","humidity":"alta","habit":"tropical"}'::jsonb, 1, 'high', NULL)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.plants ("care_instructions", "climate_zones", "container_size", "curious_facts", "difficulty", "exposure", "germination_date", "growth_rate", "hardiness_zones", "humidity", "is_active", "is_featured", "mature_height", "mature_width", "meta_description", "meta_title", "min_temp_c", "name", "native_habitat", "notes", "origin_country", "origin_region", "plant_type", "plant_use", "price", "rarity", "reference_url", "scientific_name", "short_description", "slug", "specifications", "stock_qty", "variety", "water", "weight_grams")
VALUES ('"Semisol|Suelo drenado|Riego moderado"'::jsonb, ARRAY['tropical']::text[], '0,8L', '"Cícada robusta | Muy rara"'::jsonb, 'advanced', ARRAY['semisol']::text[], '2022', 'Lento', ARRAY['10a','10b']::text[], 'medium', TRUE, FALSE, '1-2m', '1-2m', 'Cícada tropical robusta de colección; requiere semisol y drenaje excelente.', 'Zamia Jamaican Giant, cícada tropical', 5, 'Zamia sp.', 'Bosque tropical estacional', 'Pertenece a un grupo de cícadas con poblaciones muy fragmentadas.', 'JM', 'Jamaica', 'other', ARRAY['interior','colección']::text[], 45, 'very_rare', 'https://www.facebook.com/groups/europeancycadsociety/posts/4527387853975146/', 'Zamia sp.', 'Cícada tropical de gran porte', 'zamia-sp-jamaican-giant', '{"soil":"drenado","growth":"lento","type":"cícada"}'::jsonb, 2, '"Jamaican Giant"', 'medium', NULL)
ON CONFLICT (slug) DO NOTHING;

COMMIT;
